New create list (draft)
mount-joy/thelist-lambda pull request #10
Opened 2020-10-28 10:37 UTC by Joseph-Cashmore

An attempt at getting the POST list request working. I seem to have one error left to do with a mismatch calling strings and pointers. Not sure if I know enough to get it fixed on my own.

2020-10-28 19:40 UTC, samstradling commented on handlers/postList.go
> +	return listID, g.db.CreateList(listID)
CreateList takes a pointer to a string:

https://github.com/mount-joy/thelist-lambda/blob/81e77cce24a11e3ecacd1876907ff082bbc154c9/db/createList.go#L8

So this should be:

```suggestion
	return listID, g.db.CreateList(&listID)
```

2020-11-01 10:26 UTC, samstradling commented
@Joseph-Cashmore I think something odd has happened with the branches here - maybe from branching off a PR that was squashed as it was merged. Let me know if you need a hand fixing it.

2020-11-04 18:13 UTC, Joseph-Cashmore commented
Having some real problems with docker, so unfortunately I haven't been able to test this, but it builds successfully. I think more experienced hands are needed to get this to an acceptable level.

2020-11-05 18:43 UTC, alexNaylorTeece requested changes

2020-11-05 18:43 UTC, alexNaylorTeece commented on db/createList.go
> +func (d *dynamoDB) CreateList(listID *string) (error) {
I think we are no longer using a pointer to string

2020-11-05 18:43 UTC, alexNaylorTeece commented on db/createList.go
> +			"Id": { S: listID }, "Name": { S: aws.String("Shopping List") },
If you change `listID` that's passed in not to be a pointer, you will need to do `&listID` here

2020-11-05 18:43 UTC, alexNaylorTeece commented on db/createList.go
> +			"Id": { S: listID }, "Name": { S: aws.String("Shopping List") },
Do we want to hard code `Shopping List` or should that be passed in as `listName` or something?

2020-11-05 18:43 UTC, alexNaylorTeece commented on handlers/postList.go
> +func (g *postList) match(request events.APIGatewayProxyRequest) bool {
Think this `g` would be a `p` (I'm assuming this is copid from `getList` or something

2020-11-05 18:43 UTC, alexNaylorTeece commented on handlers/postList.go
> +func (g *postList) handle(request events.APIGatewayProxyRequest) (interface{}, int) {
ditto with the `g`

2020-11-05 18:43 UTC, alexNaylorTeece commented on handlers/postList.go
> +func (g *postList) handle(request events.APIGatewayProxyRequest) (interface{}, int) {
This will mean you need to change g to p in a few places

2020-11-05 18:43 UTC, alexNaylorTeece commented on handlers/postList.go
> +type postList struct {
create list or post list?

2020-11-10 09:31 UTC, closed without merging