Add update item endpoint
mount-joy/thelist-lambda pull request #9
Opened 2020-10-25 20:20 UTC by samstradling

Adds the endpoint to update items.

2020-11-03 18:02 UTC, alexNaylorTeece requested changes

2020-11-03 18:02 UTC, alexNaylorTeece commented on handlers/patchItem_test.go
> +			outputErr:          nil,
If `shouldCallDB` is false, you don't need to specify these

If you wanted, you could have a struct defined above `tests` that was something like:
```
type mockUpdateItem struct {
    output data.Item
    err error
}
```
and then in `tests` you could have `mockUpdateItem *mockUpdateItem`
You could then use `tt.mockUpdateItem != nil` in place of `shouldCallDB`

Up to you though. Just different ways of doing same thing

2020-11-05 08:34 UTC, samstradling commented on db/updateItem.go
> +	if err != nil {
`err.type` doesn't seem to be a thing:
![Screenshot 2020-11-05 at 08 34 02](https://user-images.githubusercontent.com/9036408/98216945-acf4ed00-1f41-11eb-9a0a-ebb62bff4bbb.png)

2020-11-05 08:46 UTC, samstradling commented on handlers/patchItem.go
> +	err := json.Unmarshal([]byte(body), &item)
They could do it, but it'd have no effect, the same way that specifying any other random fields would have no effect

2020-11-05 09:17 UTC, samstradling commented on db/updateItem.go
> +		TableName:           aws.String(d.conf.TableNames.Items),
`Id` is the key name for the table:
https://github.com/mount-joy/thelist-lambda/blob/4c84eb04a9290e547aef9f57e5cafadee6f3a680/cf/1.tables.yml#L20-L24

2020-11-05 09:17 UTC, samstradling commented on db/updateItem.go
> +		ConditionExpression: aws.String("attribute_exists(Id) AND attribute_exists(ListId)"),
`Id` is the key name for the table:
https://github.com/mount-joy/thelist-lambda/blob/4c84eb04a9290e547aef9f57e5cafadee6f3a680/cf/1.tables.yml#L20-L24

2020-11-05 11:05 UTC, samstradling commented on db/updateItem.go
> +	if err != nil {
According to this the only thing in the error interface is `err.Error()`:
https://blog.golang.org/error-handling-and-go

2020-11-05 12:02 UTC, alexNaylorTeece commented on db/updateItem.go
> +	if err != nil {
Sorry, I missed the brackets - `err.(type)`
I've built an example of what I'm trying to say here: https://play.golang.org/p/zqM53h68Cdz

2020-11-05 12:05 UTC, alexNaylorTeece commented on handlers/patchItem.go
> +		if errors.Is(err, db.ErrorNotFound) {
Could do a switch here to avoid if in an if, but not crucial

2020-11-05 13:20 UTC, merged